name: Test

on: [pull_request]

jobs:
  build-package:
    name: Test
    runs-on: ubuntu-latest
    steps:
      - name: Set Environment Variable
        run: |
            if [[ true == "true" ]]; then
              echo "FINAL_TEST=something" >> $GITHUB_ENV
            else
              echo "FINAL_TEST=\"\"" >> $GITHUB_ENV
            fi
      
      - name: Running tests
        run: |
          echo ${{ env.FINAL_TEST }}