name: Test

on: [pull_request]

jobs:
  tests:
    uses: homagames/unity-ci-environment/.github/workflows/build-package.yml@master
    with:
      build-method: "RuntimeTester.Test"
      bare-repository: false
    secrets: inherit