name: Test

on: [pull_request]

jobs:
  build-package:
    name: Test
    runs-on: self-hosted
    steps:
      - name: Checkout repo package
        uses: actions/checkout@v3

      - uses: actions/cache@v2
        with:
          path: Library
          key: Library

      - name: Build .unitypackage for package
        uses: game-ci/unity-builder@v2
        env:
          UNITY_EMAIL: ${{ secrets.UNITY_EMAIL }}
          UNITY_PASSWORD: ${{ secrets.UNITY_PASSWORD }}
          UNITY_SERIAL: ${{ secrets.UNITY_SERIAL }}
        with:
          customParameters: "-buildTarget Android"
          buildMethod: "RuntimeTester.Test"
          allowDirtyBuild: true
          versioning: None

      - uses: actions/upload-artifact@v3
        with:
          name: Package
          path: Build/